[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "xtasks for wesl-rs"
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
lalrpop = { version = "0.23.1", default-features = false }

[lints]
workspace = true
