[package]
name = "wesl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The WESL compiler"
repository.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
annotate-snippets = "0.12.16"
anstream = "1.0.0"
derive_more = { version = "2.1.1", features = ["display"] }
glob = "0.3.4"
itertools = "0.15.0"
proc-macro2 = { version = "1.0.107", optional = true }  # dep for feature 'package'
quote = { version = "1.0.47", optional = true }  # dep for feature 'package'
serde = { version = "1.0.229", features = ["derive"] }  # dep for feature 'package'
thiserror = "2.0.21"
toml = { version = "1.1.6", default-features = false, features = ["parse", "serde", "std"] }
wesl-core = { workspace = true }
wesl-macros = { workspace = true }
wesl-quote = { workspace = true, optional = true }  # dep for feature 'eval'
wgsl-parse = { workspace = true }
wgsl-types = { workspace = true }

[dev-dependencies]
expect-test = "1.5.1"
tokio = { version = "1.53.1", features = ["macros", "rt"] }  # for testing async compile functions

[features]
eval = ["dep:wesl-quote"]
generics = ["wgsl-parse/generics"]
# Allow naga/wgpu extensions.
# They are not well-documented, the best I could find is this:
# * https://github.com/gfx-rs/wgpu/issues/4410
# * https://github.com/gfx-rs/wgpu/blob/trunk/docs/api-specs/ray_tracing.md
# * https://github.com/gfx-rs/wgpu/blob/b93b55920a978ef9f013efe8d75cb10e69488629/naga/src/valid/mod.rs#L83
# * test files in https://github.com/gfx-rs/wgpu/tree/trunk/naga/tests
#
# List of supported naga extensions:
# * 64-bit types: i64/u64/f64 and li, lu, lf literal suffixes
# * extra builtins: `subgroup_id`, `num_subgroups`, `primitive_index`, `barycentric`, `barycentric_no_perspective`, `view_index`
# * extra texel formats: see `TexelFormat`
# * `immediate` address space
# * `atomic` access mode for textures
# * ray queries API (built-in functions, constants and struct types)
# * `atomic<f32>`
# * `texture_1d_array`, `texture_storage_1d_array`, `texture_multisampled_2d_array`
# * `subgroupBallot()` with no argument (defaults to `true`)
# * `textureSampleGrad()` with 1D texture
naga-ext = ["wgsl-parse/naga-ext", "wgsl-types/naga-ext"]
package = ["dep:proc-macro2", "dep:quote"]
serde = ["wgsl-parse/serde"]

[lints]
workspace = true
