/// Include a WGSL file compiled with [`wesl::CompileResult::write_artifact`](ttps://docs.rs/wesl/latest/wesl/struct.CompileResult.html#method.write_artifact) as a string.
///
/// The argument corresponds to the `artifact_name` passed to `write_artifact`.
///
/// This is a very simple convenience macro. See the crate documentation for a usage
/// example.
#[macro_export]
macro_rules! include_wesl {
    ($artifact_name:literal) => {
        include_str!(concat!(env!("OUT_DIR"), "/", $artifact_name, ".wgsl"))
    };
}

/// The type holding the source code of external packages.
///
/// You typically don't implement this, instead it is generated for you by [`wesl::PackageBuilder`](https://docs.rs/wesl/latest/wesl/package/struct.PackageBuilder.html).
/// Crates containing shader packages export `const` instances of this type, which you can
/// then import and [add to your resolver](https://docs.rs/wesl/latest/wesl/struct.StandardResolver.html#method.add_package).
#[derive(Debug, PartialEq, Eq)]
pub struct StaticPackage {
    pub crate_name: &'static str,
    pub root: &'static StaticPackageModule,
    pub dependencies: &'static [&'static StaticPackage],
}

/// The type holding the source code of modules in external packages.
///
/// See [`StaticPackage`].
#[derive(Debug, PartialEq, Eq)]
pub struct StaticPackageModule {
    pub name: &'static str,
    pub source: &'static str,
    pub submodules: &'static [&'static StaticPackageModule],
}

/// Include a generated package.
///
/// Generates a module containing the code generated by the packager.
///
/// See [`wesl::PackageBuilder`](https://docs.rs/wesl/latest/wesl/package/struct.PackageBuilder.html) for more information about building WESL packages.
///
/// ```rust,ignore
/// # use wesl::wesl_pkg;
/// // Load package in `OUT_DIR/my_package.rs`
/// wesl_pkg!(my_package);
///
/// // make module `pub`
/// wesl_pkg!(pub my_package);
///
/// // add module attributes
/// wesl_pkg!(#[allow(clippy::all)] pub my_package);
/// ```
#[macro_export]
macro_rules! wesl_pkg {
     ($(#[$attr:meta])* $vis:vis $pkg_name:ident) => {
         $crate::wesl_pkg!($(#[$attr])* $vis $pkg_name, concat!(stringify!($pkg_name), ".rs"));
     };
     ($(#[$attr:meta])* $vis:vis $pkg_name:ident, $source:expr) => {
         $(#[$attr])* $vis mod $pkg_name {
             #![allow(non_snake_case)]
             use $crate::{StaticPackageModule, StaticPackage};
             include!(concat!(env!("OUT_DIR"), "/", $source));
         }
     };
 }
