/// The type holding the source code of external packages.
///
/// You typically don't implement this, instead it is generated for you by [`crate::PkgBuilder`].
/// Crates containing shader packages export `const` instances of this type, which you can
/// then import and [add to your resolver][StandardResolver::add_package].
#[derive(Debug, PartialEq, Eq)]
pub struct CodegenPkg {
    pub crate_name: &'static str,
    pub root: &'static CodegenModule,
    pub dependencies: &'static [&'static CodegenPkg],
}

/// The type holding the source code of modules in external packages.
///
/// See [`CodegenPkg`].
#[derive(Debug, PartialEq, Eq)]
pub struct CodegenModule {
    pub name: &'static str,
    pub source: &'static str,
    pub submodules: &'static [&'static CodegenModule],
}

/// Include a generated package.
///
/// Generates a module containing the code generated by the packager.
///
/// See [`PkgBuilder`] for more information about building WESL packages.
///
/// ```ignore
/// // Load package in `OUT_DIR/my_package.rs`
/// wesl_pkg!(my_package);
///
/// // make module `pub`
/// wesl_pkg!(pub my_package);
///
/// // add module attributes
/// wesl_pkg!(#[allow(clippy::all)] pub my_package);
/// ```
#[macro_export]
macro_rules! wesl_pkg {
    ($(#[$attr:meta])* $vis:vis $pkg_name:ident) => {
        $crate::wesl_pkg!($(#[$attr])* $vis $pkg_name, concat!(stringify!($pkg_name), ".rs"));
    };
    ($(#[$attr:meta])* $vis:vis $pkg_name:ident, $source:expr) => {
        $(#[$attr])* $vis mod $pkg_name {
            #![allow(non_snake_case)]
            use $crate::{CodegenModule, CodegenPkg};
            include!(concat!(env!("OUT_DIR"), "/", $source));
        }
    };
}

/// Include a WGSL file compiled with [`Wesl::build_artifact`] as a string.
///
/// The argument corresponds to the `artifact_name` passed to [`Wesl::build_artifact`].
///
/// This is a very simple convenience macro. See the crate documentation for a usage
/// example.
#[macro_export]
macro_rules! include_wesl {
    ($root:literal) => {
        include_str!(concat!(env!("OUT_DIR"), "/", $root, ".wgsl"))
    };
}
