#![cfg_attr(docsrs, feature(doc_cfg))]
#![doc = include_str!("../README.md")]

mod frontend;
#[cfg(feature = "eval")]
mod frontend_eval;
mod idents;
mod util;

pub(crate) use util::*;

pub mod error;
#[cfg(feature = "eval")]
pub mod eval;
pub mod mangler;
pub mod package;
pub mod pass;
pub mod resolver;
pub mod sourcemap;
pub mod toml_cfg;

pub use crate::{
    error::Error,
    frontend::*,
    mangler::Mangler,
    package::PackageBuilder,
    pass::{Feature, Features},
    resolver::{Constants, Resolver},
};

#[cfg(feature = "eval")]
pub use crate::frontend_eval::*;

// re-exports
pub use wgsl_parse::syntax;

use wgsl_parse::syntax::ModulePath;

/// Include a WGSL file compiled with [`Wesl::build_artifact`] as a string.
///
/// The argument corresponds to the `artifact_name` passed to [`Wesl::build_artifact`].
///
/// This is a very simple convenience macro. See the crate documentation for a usage
/// example.
#[macro_export]
macro_rules! include_wesl {
    ($root:literal) => {
        include_str!(concat!(env!("OUT_DIR"), "/", $root, ".wgsl"))
    };
}

/// Include a generated package.
///
/// Generates a module containing the code generated by the packager.
///
/// See [`PackageBuilder`] for more information about building WESL packages.
///
/// ```rust,ignore
/// # use wesl::wesl_pkg;
/// // Load package in `OUT_DIR/my_package.rs`
/// wesl_pkg!(my_package);
///
/// // make module `pub`
/// wesl_pkg!(pub my_package);
///
/// // add module attributes
/// wesl_pkg!(#[allow(clippy::all)] pub my_package);
/// ```
#[macro_export]
macro_rules! wesl_pkg {
     ($(#[$attr:meta])* $vis:vis $pkg_name:ident) => {
         $crate::wesl_pkg!($(#[$attr])* $vis $pkg_name, concat!(stringify!($pkg_name), ".rs"));
     };
     ($(#[$attr:meta])* $vis:vis $pkg_name:ident, $source:expr) => {
         $(#[$attr])* $vis mod $pkg_name {
             #![allow(non_snake_case)]
             use $crate::package::{StaticPackageModule, StaticPackage};
             include!(concat!(env!("OUT_DIR"), "/", $source));
         }
     };
 }
