#![cfg_attr(docsrs, feature(doc_cfg))]
#![doc = include_str!("../README.md")]

mod idents;

pub mod mangler;
pub use mangler::Mangler;

pub mod resolver;
pub use resolver::Resolver;

pub mod error;
pub use error::Error;

pub mod pass;
pub mod visit;

pub mod package;
pub mod wesl_toml;

pub mod sourcemap;

mod condcomp;
pub use condcomp::*;

mod pipeline;

mod frontend;
pub use frontend::*;

#[cfg(feature = "eval")]
mod frontend_eval;
#[cfg(feature = "eval")]
pub use frontend_eval::*;

mod util;
pub use util::*;

use wgsl_parse::syntax::ModulePath;

#[cfg(feature = "eval")]
pub mod eval;

// re-exports
pub use wesl_macros::*;
pub use wgsl_parse::syntax;

/// Include a WGSL file compiled with [`Wesl::build_artifact`] as a string.
///
/// The argument corresponds to the `artifact_name` passed to [`Wesl::build_artifact`].
///
/// This is a very simple convenience macro. See the crate documentation for a usage
/// example.
#[macro_export]
macro_rules! include_wesl {
    ($root:literal) => {
        include_str!(concat!(env!("OUT_DIR"), "/", $root, ".wgsl"))
    };
}

/// Include a generated package.
///
/// Generates a module containing the code generated by the packager.
///
/// See [`PackageBuilder`] for more information about building WESL packages.
///
/// ```ignore
/// // Load package in `OUT_DIR/my_package.rs`
/// wesl_pkg!(my_package);
///
/// // make module `pub`
/// wesl_pkg!(pub my_package);
///
/// // add module attributes
/// wesl_pkg!(#[allow(clippy::all)] pub my_package);
/// ```
#[macro_export]
macro_rules! wesl_pkg {
     ($(#[$attr:meta])* $vis:vis $pkg_name:ident) => {
         $crate::wesl_pkg!($(#[$attr])* $vis $pkg_name, concat!(stringify!($pkg_name), ".rs"));
     };
     ($(#[$attr:meta])* $vis:vis $pkg_name:ident, $source:expr) => {
         $(#[$attr])* $vis mod $pkg_name {
             #![allow(non_snake_case)]
             use $crate::{StaticModule, StaticPackage};
             include!(concat!(env!("OUT_DIR"), "/", $source));
         }
     };
 }
